export * from './index';
export { default as css } from "./css.svg"
export { default as django } from "./django.svg"
export { default as express } from "./express.svg"
export { default as fastapi } from "./fastapi.svg"
export { default as flask } from "./flask.svg"
export { default as git } from "./git.svg"
export { default as html } from "./html.svg"
export { default as javascript } from "./javascript.svg"
export { default as mysql } from "./mysql.svg"
export { default as next } from "./next.svg"
export { default as postgresql } from "./postgresql.svg"
export { default as python } from "./python.svg"
export { default as rails } from "./rails.svg"
export { default as ruby } from "./ruby.svg"
export { default as sqlite } from "./sqlite.svg"
export { default as typescript } from "./typescript.svg"
export { default as react } from "./react.svg"